#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Holberton School" > /var/www/html/index.html

odefault="/etc/nginx/sites-enabled/default"
location="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "30i $location" "$odefault"
sudo service nginx restart
