#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Holberton School" > /var/www/html/index.html

odefault="/etc/nginx/sites-enabled/default"
location="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "30i $location" "$odefault"

echo -e "Ceci n'est pas une page\n" > /var/www/html/custom_404.html
error_page="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\t root /var/www/html;\n\t\t internal;\n\t}\n"
sudo sed -i "34i $error_page" "$odefault"

sudo service nginx restart
