#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Holberton School" > /var/www/html/index.html

config="/etc/nginx/sites-available/default"
text="server {\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "0,/server {/s//$text/" "$config"

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

text="server {\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html\/;\n\t\tinternal;\n\t}"
sed -i "0,/server {/s//$text/" "$config"

sudo service nginx restart
