#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP
# status code from the Apache log file.
FILE="apache-access.log"
if [ -e $FILE ]
then
    awk '{print $1 " " $9}' $FILE
fi
