#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# but for the 9th iteration, displays Holberton School and then Hi on a new line.
cont=0
while [ $cont -lt 10 ]; do
    echo "Holberton School"
    if [ "$cont" -eq 8 ]; then
        echo "Hi"
    fi
    let cont=cont+1
done
