#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12 and display minutes from 1 to 59
hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    min=1
    while [ $min -le 59 ]; do
        echo "$min"
        let min=min+1
    done
    let hour=hour+1
done
