#!/usr/bin/env bash
# let’s configure it to our needs so that you can connect
# to a server without typing a password

host 35.229.74.86
    PasswordAuthentication no
    IdentityFile ~/.ssh/holberton
